name: Update-Starships

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update starships.json
        env:
          SECRET_STARSHIP_ID: ${{ secrets.secret_starship_id }}
        run: |
          echo "https://swapi.dev/api/starships/$SECRET_STARSHIP_ID/"
          curl -sL "https://swapi.dev/api/starships/$SECRET_STARSHIP_ID/" -o starships.json

      - name: debug
        run: cat $GITHUB_EVENT_PATH

      - name: Format branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: fmt_branch

      - name: Check for updated starships.json
        run: if (git diff-index --quiet HEAD -- starships.json); then exit 1; else exit 0; fi

      - name: Commit and Push unstaged starships
        if: success()
        run: |
          __PR_BASE_BRANCH=$(git branch --show-current)
          PR_BASE_BRANCH=${{ steps.fmt_branch.outputs.branch }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git checkout -b ${PR_BASE_BRANCH}_updated-starships
          git add starships.json
          git commit -m "[STARSHIPS] updated json"
          git push -fu origin "${PR_BASE_BRANCH}_updated-starships"
          git checkout "${PR_BASE_BRANCH}"

      - name: Submit PR to update starships
        if: success()
        uses: actions/github-script@v3
        id: set-result
        with:
          script: |
            try {
              await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "[STARSHIPS] updated json",
                head: "${{ steps.fmt_branch.outputs.branch }}_updated-starships",
                base: "${{ steps.fmt_branch.outputs.branch }}",
              })
            }catch(error){
              if(error.constructor.name === 'HttpError' && error.toString().indexOf('A pull request already exists') > 0){
                console.log('A PR exists. Skipping PR Creation.')
              } else {
                throw error
              }
            }
