name: Update-Starships

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pull_starships:
    runs-on: ubuntu-latest
    outputs:
      needs_sync: ${{ steps.is_update_required.outputs.needs_sync }}
    steps:
      - uses: actions/checkout@v2

      - name: Update starships.json
        env:
          SECRET_STARSHIP_ID: ${{ secrets.secret_starship_id }}
        run: |
          echo "https://swapi.dev/api/starships/$SECRET_STARSHIP_ID/"
          curl -sL "https://swapi.dev/api/starships/$SECRET_STARSHIP_ID/" -o starships.json

      - name: Check for updated starships.json
        id: is_update_required
        # run: if (git diff-index --quiet HEAD -- starships.json); then exit 1; else exit 0; fi
        run: if (false); then echo "::set-output name=needs_sync::${{ false }}"; else echo "::set-output name=needs_sync::${{ true }}"; fi

  push_pr:
    needs: pull_starships
    if: ${{ needs.pull_starships.outputs.needs_sync }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Format branch name
        id: fmt_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Commit and Push unstaged starships
        run: |
          __PR_BASE_BRANCH=$(git branch --show-current)
          PR_BASE_BRANCH=${{ steps.fmt_branch.outputs.branch }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git checkout -b ${PR_BASE_BRANCH}_updated-starships
          git add starships.json
          git commit -m "[STARSHIPS] updated json"
          git push -fu origin "${PR_BASE_BRANCH}_updated-starships"
          git checkout "${PR_BASE_BRANCH}"

      - name: Submit PR to update starships
        uses: actions/github-script@v3
        id: set-result
        with:
          script: |
            try {
              await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "[STARSHIPS] updated json",
                head: "${{ steps.fmt_branch.outputs.branch }}_updated-starships",
                base: "${{ steps.fmt_branch.outputs.branch }}",
              })
            }catch(error){
              console.log('#####ERROR', error.name, error.status, error)
              if(error.name === 'HttpError' && error.status === 422 && error.toString().indexOf('A pull request already exists') > 0){
                console.log('A PR exists. Skipping PR Creation.')
              } else {
                throw error
              }
            }
