name: Update-Starships

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update starships.json
        run: curl -sL https://swapi.dev/api/starships/12/ -o starships.json

      - name: debug
        run: cat $GITHUB_EVENT_PATH

      - name: Format branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: fmt_branch

      - name: Check for updated starships.json
        run: git diff-index --quiet HEAD -- starships.json

      - name: Commit and Push unstaged starships
        if: failure()
        run: |
          __PR_BASE_BRANCH=$(git branch --show-current)
          PR_BASE_BRANCH=${{ steps.fmt_branch.outputs.branch }}
          git checkout -b ${PR_BASE_BRANCH}_updated-starships
          git add starships.json
          git commit -m "[STARSHIPS] updated json"
          git push -u origin ${PR_BASE_BRANCH}_updated-starships
          git checkout ${PR_BASE_BRANCH}

      - name: Submit PR to update starships
        if: success()
        uses: actions/github-script@v3
        id: set-result
        with:
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "[STARSHIPS] updated json",
              head: ${{ steps.fmt_branch.outputs.branch }}_updated-starships,
              base: ${{ steps.fmt_branch.outputs.branch }},
            })
